### ISSUE TITLE
Ability to remove specific response headers such as "Content-Security-Policy"

### ISSUE THREAD

**Issue by ManoharShenoy** [ganskef/MoCuishle#11]
We are using "Mo Cuishle" to inject JavaScript code that can perform "Screen capture". The problem we are facing is that if the page contains response header "Content-Security-Policy", it blocks the loading of the JavaScripts (hosted on localhost) to do the screen capture. So, it is necessary to temporarily remove this "response header" so that the screen capture can move forward.

We need a configuration (within "Mo Cuishle") to remove specific response header(s) so that the response (from "Mo Cuishle") can be consumed by downstream tools.

For now, I have locally modified OkHttpProxy.writeHeaders to ignore "Content-Security-Policy" headers so that our work can move forward.

**Comment by ganskef** [comment]
Thank you for your interest in Mo Cuishle. 

If you only use an interception proxy to inject Java Script, I think it's better to take the okproxy module and customize it with OkHttpClient [interceptors](https://square.github.io/okhttp/features/interceptors/). It's possible to add your own interceptor and network interceptor implementations in [InterceptionProxy](https://github.com/ganskef/MoCuishle/blob/master/mocuishle-okproxy/src/main/java/de/ganskef/okproxy/InterceptionProxy.java#L110) constructor with `OkHttpClient.Builder`.

      InterceptionProxy server =
          new InterceptionProxy(port, new Impersonation.Builder(), new OkHttpClient.Builder());


Mo Cuishle contains a lot of overhead, if I have the right idea of your application. Do you have published your application somewhere?

**Comment by ManoharShenoy** [comment]
We are using "Mo Cuishle" proxy to remove the usage of browser extensions for one of our products. Hence, I am not at a liberty to publish the application anywhere.

Having said that, if you have already developed something similar & are willing to share, I will be happy to look at it if "Mo Cuishle" proxy cannot meet desired performance requirements.
