### ISSUE TITLE
HTTPS webpages do not load on Firefox 120.0

### ISSUE THREAD

**Issue by ManoharShenoy** [ganskef/MoCuishle#12]
After configuring "Mo Cuishle" as a proxy using "Manual Proxy Configuration" within Firefox (snapshot embedded below)
![image](https://github.com/ganskef/MoCuishle/assets/130396696/033e43c1-6bae-4724-b73b-8ff9c6896d78)
and configuring the certificate as shown below.
![image](https://github.com/ganskef/MoCuishle/assets/130396696/ec79d3cf-54cd-4897-b01f-d8d1cdedcb52)
I keep getting the below error.
![image](https://github.com/ganskef/MoCuishle/assets/130396696/3f17f405-0058-4751-9b79-d9f0db42b8d1)

Note that this works without issues for both "Microsoft Edge" & "Google Chrome".

**Comment by ganskef** [comment]
Thank you for your interest in Mo Cuishle. ~~You need to import your Certificate Agency in the browser and allow it to trust websites. Mo Cuishle has generated a `mocuishle.pem` file in the `MoCuishle` directory at first launch.~~ You've done this already, sorry. 

I'm using Mo Cuishle with Firefox browsers, verified today: Debian 115.5.0esr, Arch Linux **120.0**, Windows 120.0.1, macOS 120.0.1. I can't reproduce your issue, maybe I have to check the Developer Edition too.

I've tried do describe ~~it~~ certificates [here](https://github.com/ganskef/MoCuishle/tree/master#browser-certificate), but it could be better :-). Please have a look at this [older documentation](https://github.com/ganskef/LittleProxy-mitm#get-it-up-and-running) or in the sophisticated [mitmproxy documentation of certificate authority](https://docs.mitmproxy.org/stable/concepts-certificates/#the-mitmproxy-certificate-authority) to see what happens.

~~And yes, I have to improve the Mo Cuishle setup documentation.~~ Out of scope here. 

Sorry, I've misunderstood your request. I'll investigate it with the most recent Firefox version. -> **done, it works for me** Please delete the certificate from ~~**Your Certificates**~~ and import it in **Authorities** like this:

![image](https://github.com/ganskef/MoCuishle/assets/10618502/8813fdbd-65c8-4dbd-9e3e-74a4afdaa7fe)

So, I'll have to improve the documentation, I think :-).

**Comment by ManoharShenoy** [comment]
Thank you. I was importing the mocuishle.p12 file directly into Firefox due to which it was showing up within "Certificate Manager > Your Certificates". Once I removed this certificate & imported the mocuishle.pem (using "Import" functionality of "Certificate Manager > Authorities"), it started working correctly.
